// ------------------------------------------------------------------------------------------------
// ----------------------------------- DO NOT EDIT THIS FILE --------------------------------------
// ------------------------------------------------------------------------------------------------

// Handle JIP / Parameter
if ("A3G_Template_AllowJip" call bis_fnc_getParamValue >= 1) then {
	_player = _this select 0;
	_didJIP = _this select 1;
	if (_didJIP && time > ("A3G_Template_JipTime" call bis_fnc_getParamValue)) then {
		_player setDamage 1;
	};
};

// Handle server side client side custom scripting
[] call compile preprocessFile "config\generic\initPlayerServer.sqf";