// ------------------------------------------------------------------------------------------------
// ----------------------------------- DO NOT EDIT THIS FILE --------------------------------------
// ------------------------------------------------------------------------------------------------

if( "A3G_Template_RemoveLoot" call bis_fnc_getParamValue >= 1 ) then {
  //["A3G_Template_Loot_EventId", "onEachFrame", A3G_Template_fnc_LootWatchdog] call bis_fnc_addStackedEventHandler;
};


// Handle server side custom scripting
[] call A3G_Template_fnc_InitServer;