// ------------------------------------------------------------------------------------------------
// ----------------------------------- DO NOT EDIT THIS FILE --------------------------------------
// ------------------------------------------------------------------------------------------------

// Handle JIP / Parameter
_player = _this select 0;
_didJIP = _this select 1;
A3G_Template_Parameters_JipTime = ["A3G_Template_JipTime", -1] call bis_fnc_getParamValue;

if(A3G_Template_Parameters_JipTime != -1 && A3G_Template_Parameters_JipTime < time && _didJIP) then {
  _player setDamage 1;
};

if( !isNil "A3G_Template_Safezone_Markers" ) then {
  // Make an event for firing, this is needed for the protection zone
  _player addEventHandler ["Fired", A3G_Template_fnc_SafeZoneEventHandler];
};


// Handle server side client side custom scripting
_this call A3G_Template_fnc_InitPlayerServer;