// ------------------------------------------------------------------------------------------------
// ----------------------------------- DO NOT EDIT THIS FILE --------------------------------------
// ------------------------------------------------------------------------------------------------

if( "A3G_Template_RemoveLoot" call bis_fnc_getParamValue >= 1 ) then {
  [] spawn A3G_Template_fnc_LootWatchdog;
};


// Handle server side custom scripting
[] call A3G_Template_fnc_InitServer;