// ------------------------------------------------------------------------------------------------
// ----------------------------------- DO NOT EDIT THIS FILE --------------------------------------
// ------------------------------------------------------------------------------------------------

if( ["A3G_Template_RemoveLoot", 0] call bis_fnc_getParamValue >= 1 ) then {
  [] spawn A3G_Template_fnc_LootWatchdog;
};

if( ["A3G_Template_LockVehicles", 0] call bis_fnc_getParamValue >= 1) then {
  [] spawn A3G_Template_fnc_LockVehiclesWatchdog;
};


// Handle server side custom scripting
[] call A3G_Template_fnc_InitServer;